SHOW DATABASES;

USE JULIST;
SHOW TABLES;
/*255BYTES 는 최대 85자 까지 가능합니다.*/
CREATE TABLE IF NOT EXISTS MEMBER(
	MEM_NO INT NOT NULL,
    MEM_EMAIL VARCHAR(45) NOT NULL,
    MEM_NM VARCHAR(45) NOT NULL,
    MEM_GNDR CHAR(1) NOT NULL,
    MEM_BIRTH VARCHAR(50) NOT NULL,
    MEM_HPNO VARCHAR(50) NOT NULL,
    MEM_JOIN_DATE VARCHAR(50) ,
    MEM_SEC_DATE VARCHAR(50),
    MEM_IMG_PATH TEXT
);

SHOW TABLES;

CREATE TABLE IF NOT EXISTS BUCKET(
	BUCKET_NO INT NOT NULL PRIMARY KEY,
    BUCKET_NM VARCHAR(50) NOT NULL,
    BUCKET_PRO_DATE VARCHAR(50),
    BUCKET_DEL_DATE VARCHAR(50),
    BUCKET_EXPLAN VARCHAR(255),
    BUCKET_CONST VARCHAR(255),
    BUCKET_IMG_PATH TEXT
);

CREATE TABLE IF NOT EXISTS BUCKET_MEMBER(
	BUCKET_NO INT NOT NULL,
    MEM_NO INT NOT NULL ,
    BUCKET_JOIN_DATE VARCHAR(255),
    BUCKET_SEC_DATE VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS LIST(
	LIST_NO INT NOT NULL PRIMARY KEY,
    BUCKET_NO INT NOT NULL,
    LIST_TITLE VARCHAR(255),
    LIST_CNTN VARCHAR(255),
    LIST_PRO_DATE VARCHAR(255),
    LIST_DEL_DATE VARCHAR(255),
    LIST_CONST_MEM INT,
    LIST_PROCEED CHAR(1),
    LIST_PRE_DATE VARCHAR(50),
    LIST_FIN_DATE VARCHAR(50),
    LIST_LEVEL CHAR(1)
);

CREATE TABLE IF NOT EXISTS USAGE_HISTORY(
	LIST_NO INT NOT NULL,
    COST_NO INT NOT NULL,
    USA_CNT VARCHAR(255),
    USA_DATE VARCHAR(255),
    USA_MEM INT
);


CREATE TABLE IF NOT EXISTS COST(
	COST_NO INT NOT NULL PRIMARY KEY,
    COST_NN VARCHAR(50)
);


SHOW TABLES;